version: '3.8'
services:

    # PostgreSQL
    postgres:
        image: postgres:11-alpine
        environment:
            POSTGRES_PASSWORD: 'secret'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'postgres'
        expose:
            - 5432
        ports:
            - 5432:5432
